# Generated by Django 3.1.4 on 2021-10-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='data',
        ),
        migrations.AddField(
            model_name='account',
            name='account_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
