# Generated by Django 3.1.4 on 2021-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_api', '0002_auto_20211001_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='index',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.TextField(default=0),
        ),
    ]
